## The following is a set of default values for prometheus server helm chart which enable remoteWrite to AMP
## For the rest of prometheus helm chart values see: https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml
##
serviceAccounts:
  server:
    name: amp-iamproxy-ingest-service-account
    annotations:
      eks.amazonaws.com/role-arn: ${arn:aws:iam::683041620920:role/amp-iamproxy-ingest-role}
server:
  remoteWrite:
    - url: https://aps-workspaces.${us-east-1}.amazonaws.com/workspaces/${ws-d99d59af-640d-4c2e-885b-fa7df32e147c}/api/v1/remote_write
      sigv4:
        region: ${us-east-1}
      queue_config:
        max_samples_per_send: 1000
        max_shards: 200
