apiVersion: v1
kind: ReplicationController
metadata:
  name: flask
spec:
  replicas: 1 # Specify the desired number of replicas here
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    app: flask
  template:
    metadata:
      name: flask
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: quantumstatic/assignment2:v1.5 #flask_image
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: "mongo-service"
            - name: MONGO_PORT
              value: "27017"
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
